# Generated by Django 4.1.5 on 2023-02-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_post_timestamp2_post_update2"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="timestamp2",),
        migrations.RemoveField(model_name="post", name="update2",),
    ]
